spring:
  datasource:
    url: jdbc:mysql://192.168.120.20:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.120.20
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
